(function() {var implementors = {};
implementors["tensorflow"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"tensorflow/struct.ImportGraphDefOptions.html\" title=\"struct tensorflow::ImportGraphDefOptions\">ImportGraphDefOptions</a>","impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"tensorflow/struct.OperationDescription.html\" title=\"struct tensorflow::OperationDescription\">OperationDescription</a>&lt;'a&gt;","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"tensorflow/struct.Function.html\" title=\"struct tensorflow::Function\">Function</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"tensorflow/struct.Session.html\" title=\"struct tensorflow::Session\">Session</a>","impl&lt;'l&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"tensorflow/struct.StepWithGraph.html\" title=\"struct tensorflow::StepWithGraph\">StepWithGraph</a>&lt;'l&gt;","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"tensorflow/struct.Status.html\" title=\"struct tensorflow::Status\">Status</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"tensorflow/struct.SessionOptions.html\" title=\"struct tensorflow::SessionOptions\">SessionOptions</a>","impl&lt;T:&nbsp;<a class=\"trait\" href=\"tensorflow/trait.TensorType.html\" title=\"trait tensorflow::TensorType\">TensorType</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"tensorflow/struct.TensorDataCRepr.html\" title=\"struct tensorflow::TensorDataCRepr\">TensorDataCRepr</a>&lt;T&gt;","impl&lt;T:&nbsp;<a class=\"trait\" href=\"tensorflow/trait.TensorType.html\" title=\"trait tensorflow::TensorType\">TensorType</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"tensorflow/struct.TensorDataNoCRepr.html\" title=\"struct tensorflow::TensorDataNoCRepr\">TensorDataNoCRepr</a>&lt;T&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
