(function() {var implementors = {};
implementors["tensorflow"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"tensorflow/struct.ImportGraphDefOptions.html\" title=\"struct tensorflow::ImportGraphDefOptions\">ImportGraphDefOptions</a>",synthetic:false,types:["tensorflow::graph::ImportGraphDefOptions"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"tensorflow/struct.ImportGraphDefResults.html\" title=\"struct tensorflow::ImportGraphDefResults\">ImportGraphDefResults</a>",synthetic:false,types:["tensorflow::graph::ImportGraphDefResults"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"tensorflow/struct.OperationDescription.html\" title=\"struct tensorflow::OperationDescription\">OperationDescription</a>&lt;'a&gt;",synthetic:false,types:["tensorflow::graph::OperationDescription"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"tensorflow/struct.Function.html\" title=\"struct tensorflow::Function\">Function</a>",synthetic:false,types:["tensorflow::graph::Function"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"tensorflow/struct.Session.html\" title=\"struct tensorflow::Session\">Session</a>",synthetic:false,types:["tensorflow::session::Session"]},{text:"impl&lt;'l&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"tensorflow/struct.SessionRunArgs.html\" title=\"struct tensorflow::SessionRunArgs\">SessionRunArgs</a>&lt;'l&gt;",synthetic:false,types:["tensorflow::session::SessionRunArgs"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"tensorflow/struct.Status.html\" title=\"struct tensorflow::Status\">Status</a>",synthetic:false,types:["tensorflow::Status"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"tensorflow/struct.SessionOptions.html\" title=\"struct tensorflow::SessionOptions\">SessionOptions</a>",synthetic:false,types:["tensorflow::SessionOptions"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
