(function() {var implementors = {};
implementors["byteorder"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"enum\" href=\"byteorder/enum.BigEndian.html\" title=\"enum byteorder::BigEndian\">BigEndian</a>",synthetic:false,types:["byteorder::BigEndian"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"enum\" href=\"byteorder/enum.LittleEndian.html\" title=\"enum byteorder::LittleEndian\">LittleEndian</a>",synthetic:false,types:["byteorder::LittleEndian"]},];
implementors["tensorflow"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"enum\" href=\"tensorflow/enum.AttrType.html\" title=\"enum tensorflow::AttrType\">AttrType</a>",synthetic:false,types:["tensorflow::graph::AttrType"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"enum\" href=\"tensorflow/expr/enum.OpLevel.html\" title=\"enum tensorflow::expr::OpLevel\">OpLevel</a>",synthetic:false,types:["tensorflow::expr::OpLevel"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"enum\" href=\"tensorflow/enum.Code.html\" title=\"enum tensorflow::Code\">Code</a>",synthetic:false,types:["tensorflow::Code"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"enum\" href=\"tensorflow/enum.DataType.html\" title=\"enum tensorflow::DataType\">DataType</a>",synthetic:false,types:["tensorflow::DataType"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"tensorflow/struct.QInt8.html\" title=\"struct tensorflow::QInt8\">QInt8</a>",synthetic:false,types:["tensorflow::QInt8"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"tensorflow/struct.QUInt8.html\" title=\"struct tensorflow::QUInt8\">QUInt8</a>",synthetic:false,types:["tensorflow::QUInt8"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"tensorflow/struct.QInt16.html\" title=\"struct tensorflow::QInt16\">QInt16</a>",synthetic:false,types:["tensorflow::QInt16"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"tensorflow/struct.QUInt16.html\" title=\"struct tensorflow::QUInt16\">QUInt16</a>",synthetic:false,types:["tensorflow::QUInt16"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"tensorflow/struct.QInt32.html\" title=\"struct tensorflow::QInt32\">QInt32</a>",synthetic:false,types:["tensorflow::QInt32"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"tensorflow/struct.Shape.html\" title=\"struct tensorflow::Shape\">Shape</a>",synthetic:false,types:["tensorflow::Shape"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
