(function() {var implementors = {};
implementors["tensorflow"] = ["impl&lt;T: <a class='trait' href='tensorflow/trait.TensorType.html' title='tensorflow::TensorType'>TensorType</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='tensorflow/struct.Buffer.html' title='tensorflow::Buffer'>Buffer</a>&lt;T&gt;","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='tensorflow/struct.OperationDescription.html' title='tensorflow::OperationDescription'>OperationDescription</a>&lt;'a&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='tensorflow/struct.SessionWithGraph.html' title='tensorflow::SessionWithGraph'>SessionWithGraph</a>","impl&lt;'l&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='tensorflow/struct.StepWithGraph.html' title='tensorflow::StepWithGraph'>StepWithGraph</a>&lt;'l&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='tensorflow/struct.Status.html' title='tensorflow::Status'>Status</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='tensorflow/struct.SessionOptions.html' title='tensorflow::SessionOptions'>SessionOptions</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='tensorflow/struct.Session.html' title='tensorflow::Session'>Session</a>","impl&lt;'l&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='tensorflow/struct.Step.html' title='tensorflow::Step'>Step</a>&lt;'l&gt;","impl&lt;T: <a class='trait' href='tensorflow/trait.TensorType.html' title='tensorflow::TensorType'>TensorType</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='tensorflow/struct.Tensor.html' title='tensorflow::Tensor'>Tensor</a>&lt;T&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
